TTM-9 Repository Design DONE
Liannhar/Tabletop_Mania pull request #1
Opened 2023-02-26 18:08 UTC by Liannhar

2023-02-26 18:11 UTC, Liannhar commented
Непон а ошибку то они поправили или нет?

2023-02-27 19:26 UTC, Prosefionol commented
На ветке TTM-9 неправильное описание проекта. Надо было на TTM-9 менять описание, а не на мейне. Потом после мёрджа оно бы изменилось на нормальное, а ща всё будет наоборот, наверное)))

2023-02-27 19:34 UTC, Prosefionol requested changes
У нас на ветке TTM-9 неправильное описание проекта. Мне кажется, что появятся проблемы после мёрджа из-за того, что кто-то пушит в main напрямую)))

2023-02-27 19:34 UTC, Prosefionol commented on app/src/main/res/values/strings.xml
> +    <string name="app_name">TabletopApplication</string>
Tabletop_Mania

2023-02-28 10:48 UTC, Liannhar commented on app/src/main/res/values/strings.xml
> +    <string name="app_name">TabletopApplication</string>
да ладно если что поменяем потом), вопрос с нерабочей штукой скорее

2023-02-28 18:13 UTC, closed without merging